### ISSUE TITLE
5.0

### ISSUE THREAD

**Issue by bf4** [metricfu/metric_fu#113]
- See [Roadmap](https://github.com/metricfu/metric_fu/wiki/Roadmap)
- See [Code tools](https://github.com/metricfu/metric_fu/wiki/Code-Tools)
- See [TODO](https://github.com/metricfu/metric_fu/blob/master/TODO.md#features)

Checklist items to be added and updated. Currently a bit of copypaste
### Plugin System / Modularity
- [ ] Tease apart how Hotspots are calculated and compared. #77 https://github.com/metricfu/metric_fu/commit/f96549 #127
  - metric, problem, score, weight, line, file, trend? suggestion?, problem_type (file, class, method)
- [x] Each metric configures itself and adds itself to a list of configured plugins #91
- [ ]  Rearrange classes, files, and narrow each classes public api #139
- [x] Plugins can use an Environment object to check for ruby version, engine, capabilities, os, etc.
- Reduce class responsibilities.  Commenting the top of each class with its responsibilities should help
  - [x] Make a proper metric grapher subclass
  - [x] Make a proper individual metric configuration subclass
  - [x] ~~Make a proper formatter object~~
  - [x] Make a proper metric runner object
  - [x] Get rid of how MetricFu and MetricFu::Configuration reach into each other back and forth.
- [x] Logic to enable or skip metrics
- [ ] Consider making a linter to validate metric plugins, like [ActiveModel::Lint::Tests](http://yehudakatz.com/2010/01/10/activemodel-make-any-ruby-object-feel-like-activerecord/) so that external metric_fu plugins can easily test themselves.
- [ ] Extract out metrics into gems: esp. cane, saikuro, roodi, rcov. See [Code Tools](https://github.com/metricfu/metric_fu/wiki/Code-Tools) for consideration of what the core functionality should be
### Enhancements
- [x] Switch from `rake stats` to code_metrics. #108 
- [x] ~~Add Formatters to enable output customization~~
- [x] Be able to run metric tools from metric_fu without shelling out
- [ ] Make it easier to whitelist metrics when running from the commandline (cli)
- Surface configurable options.  (Right now you basically need to look in configuration.rb for symbols)
  - [x] environment: rail? mri? jruby? ripper? cruise_control? osx?
  - [ ] logging: log_level, output destination
  - [ ] io: directories( code_dirs, base_dir, scratch_dir, output_dir, data_dir, roo_dir, template_dir)
  - [ ] reporting: templates classes, selectedd template, link_prefix, syntax_highlighting, open report in browser?, graph engine
  - [ ] formatters: available and enabled
  - [ ] metrics: enabled metrics and config #126
  - [ ] any library extensions
  - [ ] error behavior
- [x] Add configurable Logger to all output streams, with a `log_level` e.g. debug, info, warn, fatal
- [ ] Be able to specify folders to run against rather than just app and lib #129 
- [ ] Be able to generate historical metrics for eg gem releases (tagged with appropriate date). file format should be sequential by data, e.g. yyyymmdd-sequencenumber-fingerprint.yml where fingerprint method can be configured. Possibly use git for-each tag  #107 #96 #188
- [x] Be able to set run date on the metric reports so that we can generate historical metrics. 
- [ ] Identify trends, make suggestions?
- Errors
  - [ ] Have an ErrorHandler with hooks, failure messages, and can output debug-info to paste into issues
  - [ ] Also have ExitCodes.
- [x] Environment class that knows the ruby version, engine, ripper support, any errors, log level, operating system, artifact / output directory
- [x] Optionally open a browser window, see [launchy](https://github.com/copiousfreetime/launchy)
- [x] Add commandline --debug-info flag to output info that can be pasted into an issue  #71, #118
- [ ] Show what file a metric fails processing on, when available #68 
- [ ] Consider replacing churn with turbulence #86 
### Bugs
- [ ] Flog metrics don't consistently return file paths or line numbers, why? #66 
- [x] Handle Encoding issues in MetricFu and metric libraries. #120
- [x] Handle failures in non-MRI rubies with incomplete ripper support, e.g. JRuby might crash on cane #131
- [x] set_code_dirs check for existence #129 
### Analysis
- [x] Make the Location and LineNumber (rcov, reek, saikuro) classes work
- [ ] Clarify hotspot weighting See https://github.com/metricfu/metric_fu/commit/f9654924b28
### Testing
- [x] Fix specs to run with config.order = 'random' #112 
- [ ] Test against a dummy rails app.
- [ ] Remove / Modify Devver code from the generators/hotspots_spec and base/hotspot_analzyer_spec
- [ ] Add (pending) tests
- [x] Remove useless tests #77
### Reporting
- [x] Make the graphs prettier. See turbulence, simplecov.
- [ ] Make the hotspots page prettier
- For HTML pages
  - [ ] use pjax to make it faster
  - [ ] add more links between reports to make exploration easier
### Documentation
- [ ] Understand and explain how each metric can be used, purpose of metric. e.g. complexity, duplication, smells, coverage, security, style, documentation
- [ ] Use yard doc, remove outdated comments
- [x] Keep README up to date #114 
### Misc
- [ ] Stabilize release task to build gem, make checksum, add and commit, tag and push to github, push to rubygems
- [ ] Instructions for running on jenkins
- [ ] Run with `RUBYOPT=-w` and address warnings
- [ ] Consider letting RailsBestPractices run on non-rails apps. It works.
